### ISSUE TITLE
"記事リンクMarkdown"をボタンに変えてクリックしたらクリップボードにコピーするようにする

### ISSUE THREAD

**Issue by sota1235** [fortkle/owl#19]
やりたいマン

**Comment by fortkle** [comment]
許可を求めるな　PRせよ

**Comment by sota1235** [comment]
![](http://image.space.rakuten.co.jp/lg01/78/0000456878/85/img2b7cdc29zikbzj.jpeg)

**Comment by sota1235** [comment]
一応リポジトリの方ではIE+9とそれ以外のだいたいのブラウザでは動くぜ！って言ってますね。
明日会社のIEで見てみます〜
[GitHub: zeroclipboard/zeroclipboard](https://github.com/zeroclipboard/zeroclipboard)

**Comment by fortkle** [comment]
#20
